pipeline:
  name: Build two-tier-flask-app-docker-compose
  identifier: Build_two_tier_flask_app_docker_compose_1712218995088
  projectIdentifier: Temperory
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: two-tier-flask-app-docker-compose
        build: <+input>
